### ISSUE TITLE
Presentation feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-The-Plotting-Pandas#10]
Dear The Plotting Pandas: Below is the score breakdown for your presentation.

|          | Available | Earned |
|----------|-----------|--------|
| Time management     | 2         |     1   |
| Professionalism | 2         |     2   |
| Teamwork | 3         |    3    |
| Slides | 3         |    3    |
| Creativity Critical Thought | 3 | 3 |
| Content - Q1 | 6 | 6 |
| Content - Q2 | 6 |  6|
| Total    | 25        |     24   |

Feedback: I agree with having the code, but describing it took up a lot of your presentation time.

**Comment by bharath03-a** [comment]
Thanks for the feedback! Prof. @Gchism94 
We will try to reflect the given feedback in our final project.

- The Plotting Pandas
