### ISSUE TITLE
Write-up feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-The-Plotting-Pandas#11]
Dear TEAM_NAME: Below is the score breakdown for your write-up. 
## Write-up

|          | Available | Earned |
|----------|-----------|--------|
| Introduction     | 2         |    1.5    |
| Justification of approach | 6 (3/Question)         |   5.5     |
| Code | 6 (3/Question)         |    6    |
| Visualization | 8 (4/Question)         |    8    |
| Discussion | 8 (4/Question) | 7.5 |
| Total    | 30        |   28.5     |

Feedback: 
Overall - Honestly, very good. I was nitpicky in the feedback below, but its because this is close to perfect. 
Introduction - I requested 1-2 paragraphs, so this is a minor nitpicky issue
Justification - "In the main plot, our attention was directed towards the specific periods of 1990, 2000 and 2010" Why was this decision made? (Justification should be where this is first declared) 
Q2 discussion - Slightly long (requested 1-3 paragraphs)

**Comment by bharath03-a** [comment]
Thanks for the feedback! Prof. @Gchism94 
We will try to reflect the given feedback in our final project.

- The Plotting Pandas
