### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by thanooshakarri** [INFO526-DataViz/project-01-The-Plotting-Pandas#2]
The following is the peer review of the project proposal by Scatterplot Sorcerers. The team members that participated in this review are 

- Akrant Varshney - @AkrantVarshney
- Antonio Escalante Jr - @datalyticsintel
- Thanoosha Naidu Karri- @thanooshakarri 
- Hariharan Ramesh - @hari1016

- Describe the goal of the project.
The goal of the project is to visualize and analyze deforestation-related data, specifically focusing on global forest area changes over the past three decades and the production of soybeans in Africa. 

- Describe the data used or collected.
The project uses multiple datasets related to deforestation, including data on global forest area, Brazilian forest loss, soybean usage, vegetable oil production, and deforestation by source.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
 - For Question 1 (global forest area trends), the plan involves cleaning and focusing on relevant data columns, then creating map plots to visualize changes in forest cover from 1990 to 2015.
  - For Question 2 (soybean production in Africa), the plan includes data manipulation to calculate total soybean production and to create a line graph. Additionally, there's a plan to correlate soybean production with deforestation and afforestation rates.

- Is there anything that is unclear from the proposal?
The proposal is quite clear in describing the project's objectives, data sources, and planned methods. However, some additional details on the specific visualization techniques were unclear.

- Provide constructive feedback on how the team might be able to improve their project.
It would be better if the variables in all the datasets are explained clearly.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are particularly interested in seeing the visualizations and correlations between soybean production and deforestation rates in Africa. 

- Provide constructive feedback on any issues with file and/or code organization.
No issues with file/code organization.

- (Optional) Any further comments or feedback?

**Comment by bharath03-a** [comment]
Thanks for the valuable review, we have added few variables which are our focus since there are so many variables in the dataset, it would be futile adding all of them in the proposal. 

We have made some changes based on you feedback, Thanks ! 👍 

Closing this issue since we have responded with a fix...
