### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-The-Plotting-Pandas#4]
Dear The-Plotting-Pandas: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |       3 |
| Proposal | 5         |       2 |
| Workflow | 1         |        1|
| Teamwork | 1         |       1|
| Total    | 10        |       8 |

Good work! Some minor issues to fix to be eligible for full credit: 
1. "# Not displaying the output since it doesn't have much significance". I would display the `describe()` code since it will also give column types. I would also just display outputs anyway, since you don't know whether it will be significant to the viewer. 
2. "So we have come with approaches for both of the questions and are described below." A little informal, rephrase to: "The following are the approaches we will be using for each question." 
3. "we are planning to clean it further to only get certain parts that are required using dplyr". Be a little more descriptive about what exactly you want from the data. 
4. It's not clear which plots specifically you will be using. Make sure this sticks out immediately to the reader.

**Comment by bharath03-a** [comment]
Hello, Prof. @Gchism94 . Thanks for your valuable feedback. We have addressed the given feedback and updated the proposal with the following changes:

- Displaying all the outputs for datasets' diagnosis containing the variable types as well.
- Rephrased some descriptions to be more formal.
- Updated our approaches with more description on what we want from the data and also the type of plots we want to use.

Thank You

> The Plotting Pandas!!!

**Comment by Gchism94** [comment]
Great work, your final score is the midpoint of the two: 10/10, 8/10 -> 9/10.
