### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by ksmadhuri** [INFO526-DataViz/project-01-The-Plotting-Pandas#9]
The following is the peer review of the Presentation proposal by [Aes-thetics-Squad]. The team members that participated in this review are 

- Sai Madhuri Kandula - @[ksmadhuri]
- [Priyarsha Vallabhaneni] - @[Priyarsha31]
- [ Jothish Kumar Polaki] - @[Jothish21]
- [Ansh Kumar Dev] -  @[Anshkumardev]

- Content: Is the research question well designed and is the data being used relevant to the research question?
Research questions were well framed, one on each dataset and the data used was indeed relevant.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
The visualizations for question 1 were interesting and interpretable especially the animation, but for question 2 maybe they could have taking a few more aspects into consideration and shown them before deciding that increase in soybean consumption was related to the decrease in the forest coverage as raised in the class.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
They did select the project after careful considerations even when they don't have geographical information for the dataset and have to externally get it.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
The slides were well organized with creative elements like groove and the logo, but also could have reduced the amount of code in the presentation.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
- They have done exceptionally for the presentation, well-coordinated and well distributed among the team.

**Comment by Gchism94** [comment]
The score based on peer-review is 4.5/5.

**Comment by bharath03-a** [comment]
Thanks for the feedback!

- The Plotting Pandas
